# SVAR - dependabot.yaml
# SPDX-FileCopyrightText: 2025 Arkadiusz Bokowy and contributors
# SPDX-License-Identifier: MIT

version: 2
updates:

  # Check for updates to GitHub Actions every month
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
